### ISSUE TITLE
Script to generate the git commands

### ISSUE THREAD

**Issue by gjhenrique** [akky/tokyo-metro#1]
Hello my friend @akky

Thanks for taking an interest at my blog post and doing the legwork to build the infrastructure from Tokyo! :smile: :jp:

Could you send me the file containing the lines and stations?

I'm planning to also include Tokyo in [https://github.com/gjhenrique/metro-clojure](https://github.com/gjhenrique/metro-clojure)

**Comment by akky** [comment]
Hi @gjhenrique ,

Thank you for asking. I had made that Tokyo commit-tree with your great tool, to show how it works to my (mostly Japanese) blog readers. However, there are two circular lines, and some exchange stations which also makes another circulations, in Tokyo data. I cut off some lines to make it work even it is incomplete. So it is pretty unbaked.

I can not find the original data I used then, but will be able to find something similar if you want.

**Comment by gjhenrique** [comment]
Hey @akky 

I imported the stations and lines from your repo, but the tool created 201 commits/stations for me, while yours has 219.
Not sure if the ordering of the lines in the JSON file mattered here.

IMO, this should be something that the tool should fix, so don't waste too much time looking for the file or trying to recreate it.
I'll try to take a diff of the stations and see what went wrong and fix this edge case

Thanks again!
